// Generado desde admin/config.yml: qué texto de la página cambia cada campo del panel.
window.MAPA_CAMPOS = {
 "seo": {
  "Título de la pestaña del navegador": "seo.titulo",
  "Descripción que aparece en Google": "seo.descripcion"
 },
 "marca": {
  "Palabra escrita a mano (“Retro”)": "marca.retro",
  "Palabra grande del logo (“GREEN”)": "marca.green",
  "Iniciales del cuadradito (“RG”)": "marca.iniciales"
 },
 "encabezado": {
  "Texto chico debajo del logo": "encabezado.logo_bajada",
  "Menú: Inicio": "encabezado.nav_inicio",
  "Menú: Servicios": "encabezado.nav_servicios",
  "Menú: Nosotros": "encabezado.nav_nosotros",
  "Menú: Galería": "encabezado.nav_galeria",
  "Menú: Contacto": "encabezado.nav_contacto",
  "Botón de música": "encabezado.boton_musica",
  "Botón de reservar del menú del celular": "encabezado.mobile_reservar",
  "Título del panel de música": "encabezado.musica_titulo",
  "Botón para abrir Spotify": "encabezado.musica_boton",
  "Botón verde “Reservar turno”": "encabezado.boton_reservar"
 },
 "hero": {
  "Cartelito de arriba": "hero.insignia",
  "Frase principal": "hero.frase",
  "Frase debajo de la principal": "hero.bajada",
  "Botón “Ver servicios”": "hero.boton_servicios",
  "Sticker violeta (arriba a la derecha)": "hero.sticker_1",
  "Sticker verde (arriba a la derecha)": "hero.sticker_2",
  "Dato 1 (abajo de los botones)": "hero.dato_1",
  "Dato 2 (abajo de los botones)": "hero.dato_2",
  "Dato 3 (abajo de los botones)": "hero.dato_3"
 },
 "nosotros": {
  "Etiqueta verde de la sección": "nosotros.etiqueta",
  "Título (parte blanca)": "nosotros.titulo",
  "Título (parte verde)": "nosotros.titulo_verde",
  "Párrafo principal": "nosotros.parrafo",
  "Palabra escrita a mano del recuadro": "nosotros.cita_sello",
  "Frase destacada del recuadro": "nosotros.cita_titulo",
  "Texto del recuadro": "nosotros.cita_texto",
  "Cuadrito 1": "nosotros.punto_1",
  "Cuadrito 2": "nosotros.punto_2",
  "Cuadrito 3": "nosotros.punto_3",
  "Cuadrito 4": "nosotros.punto_4",
  "Cartelito sobre la foto": "nosotros.foto_etiqueta",
  "Sticker violeta de la foto": "nosotros.foto_sticker"
 },
 "servicios": {
  "Etiqueta verde de la sección": "servicios.etiqueta",
  "Título (parte blanca)": "servicios.titulo",
  "Título (parte verde)": "servicios.titulo_verde",
  "Texto al costado del título": "servicios.bajada",
  "Servicio 1 · línea de arriba": "servicios.s1_numero",
  "Servicio 1 · título": "servicios.s1_titulo",
  "Servicio 1 · descripción": "servicios.s1_texto",
  "Servicio 1 · línea de abajo": "servicios.s1_pie",
  "Servicio 2 · línea de arriba": "servicios.s2_numero",
  "Servicio 2 · título": "servicios.s2_titulo",
  "Servicio 2 · descripción": "servicios.s2_texto",
  "Servicio 2 · línea de abajo": "servicios.s2_pie",
  "Servicio 3 · cartelito violeta": "servicios.s3_insignia",
  "Servicio 3 · línea de arriba": "servicios.s3_numero",
  "Servicio 3 · título": "servicios.s3_titulo",
  "Servicio 3 · descripción": "servicios.s3_texto",
  "Servicio 3 · línea de abajo": "servicios.s3_pie",
  "Servicio 4 · línea de arriba": "servicios.s4_numero",
  "Servicio 4 · título": "servicios.s4_titulo",
  "Servicio 4 · descripción": "servicios.s4_texto",
  "Servicio 4 · línea de abajo": "servicios.s4_pie",
  "Servicio 5 · línea de arriba": "servicios.s5_numero",
  "Servicio 5 · título": "servicios.s5_titulo",
  "Servicio 5 · descripción": "servicios.s5_texto",
  "Servicio 5 · línea de abajo": "servicios.s5_pie",
  "Servicio 6 · cartelito verde": "servicios.s6_insignia",
  "Servicio 6 · línea de arriba": "servicios.s6_numero",
  "Servicio 6 · título": "servicios.s6_titulo",
  "Servicio 6 · descripción": "servicios.s6_texto",
  "Servicio 6 · línea de abajo": "servicios.s6_pie",
  "Enlace de cada servicio": "servicios.enlace_reservar",
  "Enlace del servicio de productos": "servicios.enlace_consultar",
  "Recuadro de abajo · título": "servicios.consulta_titulo",
  "Recuadro de abajo · texto": "servicios.consulta_texto",
  "Recuadro de abajo · botón": "servicios.consulta_boton"
 },
 "historia": {
  "Palabra escrita a mano": "historia.sello",
  "Título (parte blanca)": "historia.titulo",
  "Título (parte verde)": "historia.titulo_verde",
  "Cartelito verde": "historia.insignia",
  "Primer párrafo": "historia.parrafo_1",
  "Segundo párrafo": "historia.parrafo_2",
  "Frase destacada": "historia.cita",
  "Firma de la frase": "historia.cita_autor"
 },
 "experiencia": {
  "Palabra escrita a mano": "experiencia.sello",
  "Título (parte blanca)": "experiencia.titulo",
  "Título (parte verde)": "experiencia.titulo_verde",
  "Texto debajo del título": "experiencia.bajada",
  "Lema del recuadro violeta": "experiencia.lema",
  "Tarjeta 1 · título": "experiencia.card1_titulo",
  "Tarjeta 1 · texto": "experiencia.card1_texto",
  "Tarjeta 1 · enlace a Spotify": "experiencia.card1_enlace",
  "Cartelito sobre la foto del medio": "experiencia.foto_pie",
  "Tarjeta 2 · título": "experiencia.card2_titulo",
  "Tarjeta 2 · texto": "experiencia.card2_texto"
 },
 "clasicos": {
  "Etiqueta verde de la sección": "clasicos.etiqueta",
  "Título (parte blanca)": "clasicos.titulo",
  "Título (parte verde)": "clasicos.titulo_verde",
  "Texto al costado del título": "clasicos.bajada",
  "Juegos · línea de arriba": "clasicos.juegos_etiqueta",
  "Juegos · título": "clasicos.juegos_titulo",
  "Juegos · descripción": "clasicos.juegos_texto",
  "Películas · línea de arriba": "clasicos.pelis_etiqueta",
  "Películas · título": "clasicos.pelis_titulo",
  "Películas · descripción": "clasicos.pelis_texto"
 },
 "galeria": {
  "Etiqueta verde de la sección": "galeria.etiqueta",
  "Título (parte blanca)": "galeria.titulo",
  "Título (parte verde)": "galeria.titulo_verde",
  "Cartelito al costado del título": "galeria.insignia"
 },
 "ubicacion": {
  "Etiqueta verde de la sección": "ubicacion.etiqueta",
  "Título (parte blanca)": "ubicacion.titulo",
  "Título (parte verde)": "ubicacion.titulo_verde",
  "Palabra “Dirección”": "ubicacion.direccion_etiqueta",
  "Palabra “Horarios”": "ubicacion.horarios_etiqueta",
  "Palabra “WhatsApp”": "ubicacion.whatsapp_etiqueta",
  "Palabra “Instagram”": "ubicacion.instagram_etiqueta",
  "Botón “Cómo llegar”": "ubicacion.boton_mapa",
  "Mapa · nombre del salón": "ubicacion.mapa_nombre",
  "Mapa · barrio": "ubicacion.mapa_barrio",
  "Mapa · botón": "ubicacion.mapa_boton",
  "Mapa · cartelito de la esquina": "ubicacion.mapa_etiqueta"
 },
 "contacto": {
  "Cartelito violeta": "contacto.insignia",
  "Título (parte blanca)": "contacto.titulo",
  "Título (parte verde)": "contacto.titulo_verde",
  "Texto debajo del título": "contacto.bajada",
  "Botón de WhatsApp": "contacto.boton_whatsapp",
  "Botón de Instagram": "contacto.boton_instagram",
  "Nota de abajo": "contacto.nota"
 },
 "pie": {
  "Lema debajo del logo": "pie.lema",
  "Descripción del salón": "pie.descripcion",
  "Cartelito con la dirección": "pie.direccion",
  "Título de la columna de enlaces": "pie.nav_titulo",
  "Enlace 1": "pie.nav_1",
  "Enlace 2": "pie.nav_2",
  "Enlace 3": "pie.nav_3",
  "Enlace 4": "pie.nav_4",
  "Enlace 5": "pie.nav_5",
  "Título de la columna de redes": "pie.redes_titulo",
  "Red 1": "pie.red_instagram",
  "Red 2": "pie.red_whatsapp",
  "Red 3": "pie.red_spotify",
  "Red 4": "pie.red_mapa",
  "Recuadro de música · título": "pie.sonido_titulo",
  "Recuadro de música · texto": "pie.sonido_texto",
  "Recuadro de música · botón": "pie.sonido_boton",
  "Línea de derechos reservados": "pie.copyright",
  "Ciudad de la última línea": "pie.ciudad",
  "Lema de la última línea": "pie.lema_final",
  "Enlace al panel de administración": "pie.acceso",
  "Botón flotante del celular": "pie.boton_flotante"
 },
 "__contacto__": {
  "Número de WhatsApp": "ubicacion.whatsapp_numero",
  "Usuario de Instagram": "ubicacion.instagram_usuario",
  "Dirección del salón": "ubicacion.direccion",
  "Ciudad": "ubicacion.ciudad"
 }
};
